list_open_prs.py handle last commit push date is None
This is the traceback:

```
Traceback (most recent call last):
  File "./reports/list_open_prs.py", line 232, in <module>
    pr = PullRequest.from_api(repo_name=repo['name'], **pull_request)
  File "./reports/list_open_prs.py", line 136, in from_api
    struct.pop('commits')['nodes'][0]['commit']['pushedDate'])
  File "./reports/list_open_prs.py", line 119, in to_datetime
    return datetime.strptime(string, '%Y-%m-%dT%H:%M:%SZ')
TypeError: strptime() argument 1 must be str, not None
```

Not sure when this happens...