Set ORGANIZATIONS variable in open prs pipeline
Forgot to change `ORGANIZATION` to `ORGANIZATIONS` following updates to
the script, causing this error:

```
Traceback (most recent call last):
  File "ce-reports/reports/list_open_prs.py", line 12, in <module>
    ORGANIZATIONS = os.environ['ORGANIZATIONS'].split(',')
  File "/usr/local/lib/python3.7/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'ORGANIZATIONS'
```